{"uuid":"4b773d17-a04d-4241-9a1e-ab8a5d7cca9f","name":"Scenario Outline: Verify that user receives error for invalid python code for Max Consecutive Ones Question","children":["c7d7def0-0aa8-42ca-ad00-7e0e0ca3d573"],"befores":[{"name":"hooks.HooksPage.setUp()","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1746745447849,"stop":1746745447998}],"afters":[{"name":"hooks.HooksPage.tearDown()","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1746745454160,"stop":1746745454160}],"start":1746745447849,"stop":1746745454161}